### Numpy why use it
* Numpy is fast
* It has behind the scenes optimization written in C
* Vectorization via broadcasting (avoiding loops)
* Numpy is the basis of the pandas framework

### Things to do in Numpy
* Most useful function NumPy datatypes and attribute ( ndarray)
* Creating arrays viewing arrays and matrices 
* Manipulating and comparing arrays Sorting arrays uses cases

In [1]:
import numpy as np


### Numpy Datatypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
# Attribute associated with numpy array
a1.shape

(3,)

In [7]:
# Getting the anatomy of the numpy array whether it is a vector or a matrics
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, 

(1,)

In [10]:
a2.ndim,

(2,)

In [12]:
a3.ndim,

(3,)

In [13]:
# Getting the number of dimension for the numpy array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22, 23, 24]],
               [[25, 26, 27],
                [28, 29, 30],
                [31, 32, 33],
                [34, 35, 36]]])
a4


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [16]:
a4.shape

(3, 4, 3)

In [17]:
a4.ndim

3

In [18]:
type(a1), type(a2), type(a3), type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
a1.shape, a2.shape, a3.shape, a4.shape

((3,), (2, 3), (2, 3, 3), (3, 4, 3))

In [20]:
a1.dtype, a2.dtype, a3.dtype, a4.dtype

(dtype('int32'), dtype('float64'), dtype('int32'), dtype('int32'))

In [21]:
a1.size, a2.size, a3.size, a4.size

(3, 6, 18, 36)

# Numpy attributes includes:
* shape 
* number of dimensions ndim
* size
* data type as 'dtype' this can be integer, float,objects
* and the type() function

## Creating a dataframe from a Numpy array
* pandas does this by combining numpy arrays

In [22]:
import pandas as pd